### ISSUE TITLE
Effective Pandas I Matt Harrison I PyData Salt Lake City Meetup

### ISSUE THREAD

**Issue by salvindsouza** [numfocus/YouTubeVideoTimestamps#1]

**Comment by salvindsouza** [comment]
8:32 Contents
17:32 Memory Usage & Data Types
19:09 Chain method
27:52 Objects 
31:52 Categorical
37:25 Dates
40:32 A GLORIOUS FUNCTION
44:25 pipe function
52:11 Don't Mutate
56:08 Don't Apply
1:02:44 Master Aggregation

**Comment by logankilpatrick** [comment]
Hey! This is a great start, can you add a bit more context to these? For example, Objects could be "Objects in Python and how to use them" for example. The idea is that if someone searches for something, these timestamps would help them get to this video.

**Comment by logankilpatrick** [comment]
Added, thank you again!
