### ISSUE TITLE
Guido Van Rossum - Interview at PyData Fest Amsterdam 2020

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#10]
https://youtu.be/eJUwlzR_hCY?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ
    
Contents
0:00  - Introduction
1:25  - Resemblance between Python and ABC
2:40  - Prevalence of Python in Academia/DataScience
3:40  - Guido's new position (BDFL and steering counsel)
10:15 - Questions about steering counsel
16:55 - Adoption of Python 3 
20:45 - Parser update for CPython in 3.9
27:25 - Some words about scholarship winners
29:40 - Questions

**Comment by logankilpatrick** [comment]
Thank you!!

**Comment by stobinaator** [comment]
my pleasure!
