### ISSUE TITLE
Joel Grus- Ten Ways To Fizz Buzz| PyData Global 2020

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#11]
https://youtu.be/E7JAIF9FOnM?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ
    
Contents
0:00 - Introduction
1:55 - 1.100 print statements
2:16 - 2.if/elif/elif/else
2:34 - 3.the cycle of 15
2:58 - 4.Euclid's Solution
3:28 - 5.Trigonometry
3:56 - 6.A big number
4:21 - 7.Infinite Iterables
4:51 - 8.Random Guessing
5:29 - 9.Matrix Multiplication
5:55 - 10.Fizz Buzz in Tensorflow

**Comment by logankilpatrick** [comment]
Thank you!
