### ISSUE TITLE
Andrada Pumnea - Does hate sound the same in all languages? | PyData Berlin 2019

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#12]
https://youtu.be/xFTTHCH4yiQ?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ
    
Contents
0:00  - Introduction
1:06  - Agenda
2:53  - Transfer Learning
5:15  - Focus on low(er) resource languages
9:49  - Labeling workflow
13:55 - Training models
19:16 - Results
22:33 - Conclusion
23:45 - End of talk + Questions

**Comment by logankilpatrick** [comment]
Thank you, in general, avoid things like "conclusion, results, end of talk" and replace them with specific details
