### ISSUE TITLE
Gianluca Campanella: The unreasonable effectiveness of feature hashing | PyData London 2019

### ISSUE THREAD

**Issue by Cyborg-vs-Droids** [numfocus/YouTubeVideoTimestamps#13]
https://www.youtube.com/watch?v=XelrzDtEnPY

0:00 - About Speaker
1:00 - Introduction
1:53 - Background- Supervised ML
3:29 - Categorical Features
4:00 - One-hot encoding
4:36 - Bag of words
5:20 - High dimensional feature space
9:20 - Feature Hashing
11:26 -  Hash function
12:24 - Feature Hashing in Python
13:27 - Hashing of Unicode Strings
15:05 - Projection
15:06 - Collisions
17:58 -  Sign Functions
20:26 - Feature Hashing- Example
26:40 -  Feature Hashing- Use Case
30:10 - Library Support
31:27 - Recap
32:20 - Q&A

**Comment by logankilpatrick** [comment]
Thank you!
