### ISSUE TITLE
Ivana Seric: The evolution of basketball with data science | PyData Córdoba 2019

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#14]
https://youtu.be/exGg6J14utA?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ
    
Contents
0:00  - Introduction
3:02  - Analytics in baseball
6:35  - History about Don Knuth (Electronic Coach)
8:54  - Collected data in 1962 (just the boxscore)
10:20 - Collected data since 1996 (play-by-play)
13:56 - Early development in 2000s of tracking players in-game
15:31 - Spatio-Temporal Data
22:53 - Defensive Metrics
26:32 - Questions

**Comment by logankilpatrick** [comment]
Thanks!
