### ISSUE TITLE
Mariana Capinel: Where Linguistics meets Natural Language Processing | PyData Berlin 2019

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#15]
https://youtu.be/vesSXYx2uQw?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ

Contents
0:00  - Introduction
1:02  - History of studying languages
5:21  - 5 levels of language studying
8:19  - Word Mapping Models
9:15  - Speech recognition and linguistics
10:40 - Language models and linguistics
12:10 - End of lecture
12:50 - Questions

**Comment by logankilpatrick** [comment]
Thank you again!
