### ISSUE TITLE
Bogumił Kamiński - An introduction to DataFrames for pandas users| PyData GLobal 2020

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#16]
https://youtu.be/K2J8pwSyUMw?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ
    
Contents
0:00  - Introduction
4:19  - Hands-on 
8:05  - Reading a DataFrame
10:29 - Simple operations on a DataFrame (Julia vs Pandas)
21:37 - Aggregation functions
25:35 - Piping
27:17 - Noteworthy packages

**Comment by logankilpatrick** [comment]
For here, things like "Hands-on" should be more descriptive with respect to what is actually being done

**Comment by logankilpatrick** [comment]
Thank you again for this!
