### ISSUE TITLE
Vincent D. Warmerdam: Untitled12.ipynb | PyData Eindhoven 2019

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#17]
https://youtu.be/yXGCKqo5cEY?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ
    
Contents
0:00  - Introduction
1:05  - Agenda
1:35  - Introducing a workflow
4:15  - Live demo with bad practices
13:00 - Demo but with better practices
26:30 - scikit-lego
30:57 - last thoughts

**Comment by logankilpatrick** [comment]
Added, but in the future, these could use more depth. Thanks again!
