### ISSUE TITLE
Meirav Ben Izhak - NetworkX - your Unexpected Assistant for Clustering Analysis

### ISSUE THREAD

**Issue by geoafrikana** [numfocus/YouTubeVideoTimestamps#182]
Todo

**Comment by abremod** [comment]
https://www.youtube.com/watch?v=FYwGeQ353DY

0:19 Biography
1:26 Graphs
5:14 NetworkX
7:14 Clustering with NetworkX
12:41 Code Example
16:28 Summary
17:24 Q&A Clustering Sentences
22:40 Alternatives to NetworkX
23:27 Links
