### ISSUE TITLE
Mia Polovina: Analysing Russian Troll Tweets data with Python | PyData Warsaw 2019

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#19]
https://youtu.be/1JAhl3b3OFw?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ

Contents
0:00  - Introduction
0:35  - Background
5:31  - Online trolls and bots
9:13  - Analyzing Tweets Datasets with Python
12:30 - Difference between troll account types
12:32 - Right Troll
14:44 - Left Troll
16:21 - NewsFeed Troll
17:06 - HashtagGamer Troll
18:01 - Fearmonger Troll
19:19 - Clustering Troll Tweets with UMAP (Dimensionality reduction)
20:04 - Russian Trolls Activity over Time
26:20 - Russian Troll Activities beyond the U.S.
27:22 - Importance of problem research
30:15 - Challenges
34:20 - End of talk
34:50 - Questions

**Comment by logankilpatrick** [comment]
Thank you!
