### ISSUE TITLE
James Powell: So you want to be a Python expert? | PyData Seattle 2017

### ISSUE THREAD

**Issue by SucheG** [numfocus/YouTubeVideoTimestamps#2]
https://www.youtube.com/watch?v=cKPlPJyQrt4

Contents
0:00 - Introduction
6:39 - Python Data Model
20:51 - Meta Classes
47:21 - Decorators
1:06:31 - Generators
1:24:35 - Context Managers
1:48:25 - questions

**Comment by logankilpatrick** [comment]
Hey! Great start here, it would be awesome to get some more fidelity. I would say 1 timestamp every 10 minutes is usually pretty good for longer videos.

**Comment by logankilpatrick** [comment]
I think that would be helpful, to have, that will give them the highest amount of SEO

**Comment by logankilpatrick** [comment]
Bumping this ^
