### ISSUE TITLE
Wes McKinney: pandas in 10 minutes | Walkthrough Sep 18, 2019

### ISSUE THREAD

**Issue by kwlee2020** [numfocus/YouTubeVideoTimestamps#21]
[![Wes McKinney: pandas in 10 minutes | Walkthrough Sep 18, 2019](https://i.ytimg.com/vi/_T8LGqJtuGc/hqdefault.jpg)](https://www.youtube.com/watch?v=_T8LGqJtuGc)

Contents
0:00 - Greetings & the book
0:19 - Fast tabular data I/O
0:38 - Time series operations
0:42 - Timestamp as index
2:01 - Moving window functions
2:17 - Data alignment
3:08 - Missing data handling
4:19 - Groupby operations
5:45 - Hierarchical indexing
6:50 - Merging and joining
9:05 - Pivot tables
9:28 - Data summary, statistics
10:16 - Closing

**Comment by logankilpatrick** [comment]
Added, thank you!!
