### ISSUE TITLE
Time, Interrupted: Measuring Intervention Effects with Interrupted Time-Series Analysis - Ben Cohen

### ISSUE THREAD

**Issue by fsammarc** [numfocus/YouTubeVideoTimestamps#22]
00:46 Introduction
02:41 What is Interrupted Time Series Analysis
03:53 A/B Testing
04:53 How to measure the impact of a national TV campaign
05.44 Geo-targeting
06:25 How can we know if something we did had an effect
08:05 Counterfactuals
09:23 Interrupted Time Series
13:01 Building a time series counterfactual
14:01 Non-stationarity
15:30 Auto-correlation
16:15 Indipendent and identically distributed assumptions
17:52 What should the model include 
19:45 Prediction intervals
22:19 Prophet library
23:26 Training and prediction
24:53 Assess accuracy of the model
26:20 Compare predictions to observations
26:53 Lift analysis
27:00 Samples from posterior predictive distribution
27:31 Pointwise vs cumulative estimates
29:38 Answering probability-based questions
30:05 Threats to validity
30:53 Change in the underlying process
32:49 Confounding variables
33:47 Model misspecification
36:27 Q&A
36:35 Business applications
38:26 Situations where it worked or didn't
39:45 Comparing different channels of advertisement
40:50 Data preparation for Interrupted Time Series
41:55 Ramp-up period before measuring effect
43:06 Assessing whether the counterfactual is correct

**Comment by logankilpatrick** [comment]
Added, thank you!
