### ISSUE TITLE
Do tyres dream of electric clouds? - Tom Alisi | PyData London 2018

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#24]
https://youtu.be/ZbYoCAzgHhc

Contents
0:00  - Introduction
5:35  - Connesso
9:37  - Evaluation of tyre wear
16:38 - Connesso - High level architecture 
18:13 - Architectural choices
22:04 - Teams and Tools
26:33 - Cross functional integration
27:51 - Lessons learned
32:33 - End of talk
33:00 - Questions

**Comment by logankilpatrick** [comment]
Talks like this could use a little more depth
