### ISSUE TITLE
A/B Testing with Style - Alistair Lynn | PyDat London 2018

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#25]
https://youtu.be/H9FBrRybw6g

Content
0:00  - Introduction
1:06  - What is A/B Testing?
2:40  - Why would you do it?
5:13  - How do you do it?
8:13  - Old way
11:10 - New way
13:46 - Demo - jacquard
20:45 - How to measure test data?
22:50 - No decision rule
25:57 - Risks
29:50 - Ethics
30:45 - End of talk
31:00 - Questions

**Comment by logankilpatrick** [comment]
Added, thank you!
