### ISSUE TITLE
Rob Story - Up and Down the Python Data and Web Visualization Stack | PyData Silicon Valley 2014

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#27]
https://youtu.be/kmy-sfm3cC8

Contents
0:00  - Introduction
2:30  - Python Data visualization libraries
4:31  - The present is Web visualization
5:10  - IPython is like glue-all
5:45  - The new stack
7:43  - Demo
9:47  - Vincent Library
14:34 - GGPlot Library
17:23 - Bokeh Library
18:45 - Bearcart Library
20:41 - Seaborn Library
23:11 - Folium Library
25:30 - End of Demo
25:43 - The Future
26:46 - Sticky Library Code Example
31:42 - End of talk
32:15 - Questions

**Comment by logankilpatrick** [comment]
Thanks!
