### ISSUE TITLE
Paul Ivanov and Thomas Kluyer - The IPython Protocol, Frontends and Kernels | PyData Silicon Valley 2014

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#28]
https://youtu.be/QPimD4gL0ak

Content
0:00  - Introduction
1:25  - Paul Ivanov speaking
2:17  - What is IPython? IP[y]:
3:14  - A not perfect Analogy
4:19  - Kernel
5:24  - Anatomy of a Kernel message
6:07  - Client
7:01  - Why have many clients?
9:56  - vim-ipython demo
12:26 - bipython demo
13:44 - Embed is your friend
14:50 - Thomas Kluyer speaking
16:01 - Julia
21:04 - R demo
26:33 - IPython Kernels
28:25 - Sneak preview of IPython 3.0
30:29 - End of talk
30:42 - Questions

**Comment by logankilpatrick** [comment]
Added, thanks!
