### ISSUE TITLE
Christopher Roach - Visualizing Geographic Data With Python | PyData San Francisco 16

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#29]
https://youtu.be/ZIEyHdvF474?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ

Content
0:00  - Introduction
0:49  - Reasons for this talk
1:52  - Overview
3:07  - The power of maps
5:35  - The problem with maps
10:05 - How are maps made
14:55 - Good map design
22:07 - Examples
23:45 - Extras
28:10 - Questions

**Comment by logankilpatrick** [comment]
Done, thanks!
