### ISSUE TITLE
Nick Jones, Sam Barrows: Uber's Synthetic Control | PyData Amsterdam 2019

### ISSUE THREAD

**Issue by fsammarc** [numfocus/YouTubeVideoTimestamps#3]
0.05 - Introduction
0.36 - What to do when A/B testing is not possible
2.00 - Motivating example: Cash trips at Uber
3.47 - Experiment: Tell drivers if a trip is cash
5.07 - Why an A/B Test doesn't work here: Spillover effects
6.53 - What to do instead of A/B: Look at before and after 
7.40 - What to do instead of A/B: Switchbacks
8.46 - What to do instead of A/B: Difference-in-Differences
10.21 - A/B Alternative: Synthetic Control
11.47 - How do we form our synthetics?
13.42 - How do we estimate treatment effect?
14.57 - Synthetic control performance
15.32 - Synthetic control implementation at Uber scale
16.25 - Other use cases for Synthetic Control at Uber: Uber POOL
18.17 - Other use cases for Synthetic Control at Uber: Surge pricing
19.04 - Limitations of Synthetic Control
22.06 - Key takeaways

**Comment by logankilpatrick** [comment]
Same as I mentioned in the other one. Thanks again, these are great!
