### ISSUE TITLE
Kashif Rasul: Intro to ConvNets | PyData Berlin 2014

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#30]
https://youtu.be/W9_SNGymRwo?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ

Content:
0:00  - Introduction
1:11  - Classification of labeled data
3:50  - Problem of object recognition in images
6:42  - Main reason for resurgence
7:47  - Higher level overview of a neural network
10:20 - How does this work?
14:20 - Multi class logistic classification
16:02 - Backward propagation
17:15 - Training a neural network
18:15 - Feature extraction in images
20:10 - What is a convolution?
23:10 - Convolutional neural networks (in Python)
24:42 - Cuda-convnet
35:05 - Regularisation
36:58 - Parallelising CNNs
40:07 - End of talk
40:40 - Questions

**Comment by logankilpatrick** [comment]
Done, thanks!
