### ISSUE TITLE
Making Computation Easier with Cool Numpy Tricks - Kirit Thadaka

### ISSUE THREAD

**Issue by John98Zakaria** [numfocus/YouTubeVideoTimestamps#32]
https://www.youtube.com/watch?v=poD8ud4MxOY

Content:

0:00 Introduction
2:26 Basic Numpy
9:38 Structured Numpy Array
11:43 Broadcasting
19:03 Fancy Indexing numpy
01:04:06 Stride Tricks
01:12:30 Einsum
01:23:47 Convolution using stride tricks and einsum

**Comment by logankilpatrick** [comment]
Thank you!
