### ISSUE TITLE
Raphael Pierzina - Kickstarting projects with Cookiecutter

### ISSUE THREAD

**Issue by mitchr1598** [numfocus/YouTubeVideoTimestamps#33]
00:00 - Welcome!
00:10 - Introduction
01:22 - Agenda
02:18 - What is Cookiecutter?
06:00 - How does Cookiecutter work?
09:20 - Create you own Cookecutter template
17:01 - Popular Cookecutter templates
19:02 - Demo: A custom Jupyter widget

**Comment by logankilpatrick** [comment]
Thank you!!!
