### ISSUE TITLE
Responsible implementation of Machine Learning models for life-and-death decision making | Eindhoven

### ISSUE THREAD

**Issue by michetonu** [numfocus/YouTubeVideoTimestamps#34]
00:00 - Welcome!
00:10 - Introduction
01:06 - Bridging the implementation gap in healthcare
02:34 - Agenda
02:55 - Pacmed Critical and the Intensive Care
06:44 - Challenges of implementing ML for life-and-death decisions
07:36 - Data Validity
14:35 - Interpretability and Auditability
19:10 - Prediction Validity
24:24 - What happens when there is a problem in production?
26:54 - Next steps
28:42 - Conclusions
30:06 - Q&A

**Comment by logankilpatrick** [comment]
Thanks so much!
