### ISSUE TITLE
Dealing with the versioning of production-ready models - Corné Vriends | PyData Eindhoven 2021

### ISSUE THREAD

**Issue by yugant10-commits** [numfocus/YouTubeVideoTimestamps#35]
0:00 - Welcome!
0:09 - Introduction
1:12 - Problem Statement
2:38 - Company Introduction
5:23 - Design Architecture
7:16 - Machine Learning Flow
8:56 - Pickling
13:29 - Solving Pickling Issue
14:26 - Possible Solutions
15:50 - 1. Portable Format (ONNX)
17:56 - 2. Containerize
19:50 - 3. Periodically Retrain
22:28 - Key Takeaways
23:35 -  Questions

**Comment by logankilpatrick** [comment]
Added, thank you!
