### ISSUE TITLE
Be kind to yourself! Spend (less) time on Data Exploration - Willem Hendriks | PyData Eindhoven 2021

### ISSUE THREAD

**Issue by arne-cl** [numfocus/YouTubeVideoTimestamps#36]
00:08 Introduction
2:05 What is Data Exploration?
2:26 "You have to get to know your data!" (Leo Breiman, https://www.youtube.com/watch?v=ZIET5K1uob8)
11:50 Pandas Profiling https://github.com/pandas-profiling/pandas-profiling
14:07 SweetVIZ https://github.com/fbdesignpro/sweetviz
15:59 DABL https://github.com/dabl/dabl
17:58 dTreeViz https://github.com/parrt/dtreeviz
19:56 dtale https://github.com/man-group/dtale
22:35 Conclusions
25:18 Q&A

**Comment by logankilpatrick** [comment]
Thank you!!
