### ISSUE TITLE
How to quickly build Data Pipelines for Data Scientists - Geert Jongen | PyData Eindhoven 2021

### ISSUE THREAD

**Issue by mraxilus** [numfocus/YouTubeVideoTimestamps#37]
00:00 Introduction
01:58 Data Pipelines
07:32 Tip 1: Define a Clear Split Between Data Engineering and Data Science
08:58 Tip 2: For the Data Pipeline Part Use Notebooks in Flows
10:34 Tip 3: Have a Sit-Down With Your Team and Decide on Standards
11:14 Tip 4: All Data You Use Needs to Have a Source
12:36 Tip 5: Prepare for Changes
13:36 Delta Lake
16:38 Demo
26:50 Conclusion

**Comment by logankilpatrick** [comment]
Thank you very much!
