### ISSUE TITLE
Tetiana Ivanova: How to become a Data Scientist in 6 months | PyData London 2016

### ISSUE THREAD

**Issue by anzelpwj** [numfocus/YouTubeVideoTimestamps#38]
https://www.youtube.com/watch?v=rIofV14c0tc

0:00 Introduction
4:56 Higher education
13:02 Things not to do
17:55 What did I do in the end?
21:51 Time discounting and willpower
26:27 Time management techniques
31:37 Networking
37:18 Resources for Data Science transition
44:34 Don’t get started
45:51 Q&A

**Comment by logankilpatrick** [comment]
Thank you, Paul!
