### ISSUE TITLE
Python and the Holy Grail of Causal Inference - Dennis Ramondt, Huib Keemink

### ISSUE THREAD

**Issue by trfore** [numfocus/YouTubeVideoTimestamps#39]
https://www.youtube.com/watch?v=HPC42U9xtQY

0:00 Introduction
0:36 What is Causal Inference
1:18 "Slogan" for the Talk
1:35 Typical Randomized Testing
2:15 Use Case 1: Heat Pump Savings
2:45 Measurement Data: Daily Gas Usage ~ Outside Temp
3:32 Experiment Setup: Heat Pump Savings
5:40 Fixing Group Imbalance
6:50 Propensity Score Matching
7:47 Recap of Heat Pump Use Case (Correcting Assumptions and Limitations)
9:07 Use Case 2: Effect of Cooler Placement
9:40 Experiment Setup: Cooler Placement
11:47 Problem 1: Test and Control Groups are Statistically Different
13:17 Code Example: Single Covariate Simulated Example 
14:01 Treatment Effect Correction
16:14 Code Example: Treatment Effect Correction
16:28 Assumptions: Conditional Mean Independence & Conditional Independence
18:44 Tree Ensemble: Virtual Twins
20:21 Results: Cooler Placement
22:18 Talk Recap
24:50 Q&A 1
26:38 Q&A 2
27:32 Q&A 3
29:00 Q&A 4
30:29 Q&A 5

**Comment by logankilpatrick** [comment]
Thanks so much!
