### ISSUE TITLE
A/B testing at Zalando: concepts and tools - Shan Huang, Grigory Bordyugov

### ISSUE THREAD

**Issue by fsammarc** [numfocus/YouTubeVideoTimestamps#4]
0.06 - Introduction
3.37 - Spurious correlations
6.31 - A/B tests
9.52 - A/B testing infrastructure at Zalando
11.58 - A/B Testing infrastructure at Zalando: software engineering perspective
16.10 - ExpAn: open-source library for analyzing A/B test results
16.58 - Hypothesis testing as a noisy binary classifier
18.00 - Example: is coin fair?
26.02 - Multiple KPIs / Endpoints testing
26.43 - Early stopping (peeking into tests)
28.02 - Going from data to statistics, from statistics to decisions
31.58 - Q&A
32.18 - Q&A: Do you use Classical tests or Bayesian tests?
33.45 - Q&A: What kind of experiments do you run?
35.08 - Q&A: What is the most egregious mistakes you have seen?

**Comment by logankilpatrick** [comment]
Added! For future reference, please use ":" instead of a "." and remove the "-" after the timestamp. Thank you again!!
