### ISSUE TITLE
Keynote: Judea Pearl - The New Science of Cause and Effect

### ISSUE THREAD

**Issue by trfore** [numfocus/YouTubeVideoTimestamps#40]
https://www.youtube.com/watch?v=ZaPV1OSEpHw

0:00 Speaker Introduction
1:00 Introduction
1:18 Talk Proverb
2:13 Talk Outline
5:11 Causal Models and the Cognitive Revolution
10:50 Typical Causal Questions & The Limitation of Standard Grammar of Science
18:15 The Ladder of Causation (3 Level Hierarchy)
26:36 Simpson's Paradox
31:00 Explainability Deep-Learning Style
34:26 Distinguish Seeing from Doing
36:19 The Two Fundamental Laws of Causal Inference
38:15 Reading Independencies
40:02 Structural Causal Model (SCM) Inference Engine
42:33 The Seven Pillars of Causal Wisdom
44:44 Pillar 5: External Validity and Sample Selection Bias
45:51 Pillar 5: The Problem in Real Life
47:06 Pillar 5: The Problem in Mathematics
49:16 Conclusion
51:56 Q&A 1: Opinion on Natural Experiments to Discover Causal Connections in Data
57:38 Q&A 2: Opinion on the Popularization of Statistics in News Media
1:01:30 Q&A 3

**Comment by logankilpatrick** [comment]
Thank you again!
