### ISSUE TITLE
James Powell: Building Web-based Analysis & Simulation Platforms | PyData London 2017

### ISSUE THREAD

**Issue by mycaule** [numfocus/YouTubeVideoTimestamps#43]
Source code: https://bit.ly/dutc-tutorial

Contents
0:07 Introduction
2:29 Getting the source code from Dropbox
12:00 Algorithm for calculating Pi Digits
17:40 Generalising the problem and serving from HTTP
21:30 Packaging to the backend code
30:38 Testing first version
32:40 Exposing the algorithm to a flask server
38:48 Testing the server with httpie
42:14 Concurrent requests
44:02 How celery and Redis solve that problem
46:00 Installing the last required packages
49:15 Running Redis
49:35 Writing the worker code
53:35 Running the celery worker
57:09 Exposing tasks management in the backend code
1:00:30 Pause, letting people catchup
1:08:40 About doing talks at PyData
1:10:40 Opinions on JavaScript and React build chain
1:13:45 Explaining what is in the Dropbox frontend folder and tooling choice
1:21:30 Writing React code
1:26:42 Running the frontend, implementing the main component
1:39:33 Finishing the HTML form
1:40:25 Wiring the frontend to the backend
1:47:43 Results from the frontend application

Original video at https://www.youtube.com/watch?v=eEXKIp8h0T0

**Comment by logankilpatrick** [comment]
Thank you! Added.
