### ISSUE TITLE
James Powell: So you want to be a Python expert? | PyData Seattle 2017

### ISSUE THREAD

**Issue by mycaule** [numfocus/YouTubeVideoTimestamps#44]
Following #2,

I think detailed bookmarks can be helpful for SEO, but also for developers if they want to rewatch something they remembered having seen in the past.

Contents
0:00 About PyData and being proficient in Python
4:09 Important features of Python and audience survey
7:40 Data model methods
10:14 `__init__` method
11:15 `__repr__` method
12:17 `__add__` method
15:51 `__len__` method
18:42 `__call__` method
20:50 Metaclasses and the problem of writing safe library code
27:00 Contraints on the library code using `assert`
32:33 Compile time vs run time executable code
34:42 Disassembling class code and using `__build_class__`
40:26 Constraining library code with the metaclass pattern
47:22 Introducing decorators
49:07 Code inspection
57:36 Writing a timer function
59:42 Decorator syntactic sugar
1:03:00 Writing a ntimes decorator
1:06:32 Wrapping functions into class
1:10:51 Eager execution
1:14:02 `__iter__` and `__next__` methods
1:17:40 yield and and the Generator syntax
1:20:35 Coroutines and interleaving
1:24:35 Context Managers
1:25:30 Setup and teardown of resources
1:28:38 Applying to SQL transactions
1:30:10 `__enter__` and `__exit__` methods
1:32:30 Links between generators and context managers
1:36:02 Refactoring the SQL query code
1:37:52 Wrapping up
1:40:04 Opinions on writing clear code in Python
1:48:18 Q&A

Mentioned references
https://docs.python.org/3/reference/datamodel.html#emulating-container-types

Original video at https://www.youtube.com/watch?v=cKPlPJyQrt4

I also think the autogenerated subtitles are quite good on this video already.

**Comment by mycaule** [comment]
@bibimorlet this video should help you between 1:36:00 and 1:38:00 around the `@contextmanager` decorator. (old question)

**Comment by logankilpatrick** [comment]
Added, thank you!
