### ISSUE TITLE
Dave Nielsen: Top 5 uses of Redis as a Database | PyData Seattle 2015

### ISSUE THREAD

**Issue by mycaule** [numfocus/YouTubeVideoTimestamps#45]
Contents
0:00 Introduction
1:56 What is Redis?
2:50 What can I do with Redis?
4:47 Who uses Redis?
5:47 Who's contributed?
6:27 Where can I get Redis?
7:23 What is Redis in details?
8:56 A cache layer, a pub/sub engine
11:46 Redis vs Memcached
13:13 Use cases: Latest items, Deletion, Leaderboards, Order users, Expires
14:50 Use cases: Counting, Unique items, Realtime stats, Pub/Sub, Queues, Caching
17:57 Data types in Redis: String, List, Set, Sorted Set
23:23 Datatypes: Hash, BitMaps, HyperLogLog
26:00 Redis in Action Book
26:20 About the ContainerDay event
26:53 Q&A

References
Redis in Action: https://www.goodreads.com/book/show/16033444-redis-in-action

Original video at https://www.youtube.com/watch?v=jTTlBc2-T9Q

**Comment by logankilpatrick** [comment]
Great! Thank you.
