### ISSUE TITLE
Rebecca Conley, Mark Lavin | You Belong with Me: Scraping Taylor Swift Lyrics with Python and Celery

### ISSUE THREAD

**Issue by mycaule** [numfocus/YouTubeVideoTimestamps#46]
0:00 Taylor Swift catalog of songs
1:20 About Celery
2:55 How Celery works
3:36 Message brokers
5:15 Choosing a broker
6:35 Storing results
9:30 Coding with Celery
15:30 Scrapping lyrics websites
16:46 Inspecting the DOM
17:13 Coding with BeautifulSoup
20:07 Getting the results and performance
22:40 Improvements: Better storage, Celery chains, groups, chords
24:15 Wrapping up: Celery is a popular as Taylor Swift for distributed tasks

The video title should actually include Celery, which is the main tech subject, it is too long from the SEO standpoint.
It only has 600 views despite the talk being quite decent.
 
I suggest using this title instead
> Rebecca Conley, Mark Lavin | Scraping Lyrics with Celery | PyData Carolinas 2016

Original video at https://www.youtube.com/watch?v=IrIu7fneP_0

**Comment by logankilpatrick** [comment]
Added both suggestions, thank you!
