### ISSUE TITLE
More About Generators - James Powell

### ISSUE THREAD

**Issue by mycaule** [numfocus/YouTubeVideoTimestamps#47]
Contents
0:00 About PyData and introducing generators
1:50 Hacking the Python `print` function
4:36 Overview of the talk
5:32 Review
6:25 Three different implementation of the `add` function
8:15 Adding a state variable, difference between class and function
11:05 A compute function with sleep
13:55 Using the generator pattern with `__iter__` and `__next__`
15:15 Differences in approaches: laziness, storage
17:27 What generators are
19:40 Pipelines and `nwise` function
21:05 Writing a basic scheduler with generators
23:05 Why they are not what you think they are
23:40 Timing code and Python not being optimal vs Perl for scientists
27:55 Have some fun, computing graphs
29:10 Implementing a graph structure with generators
31:20 Improving the design with more laziness
38:00 Final version of the code (propagation in nodes of a graph)
39:00 Conclusion

Original video at https://www.youtube.com/watch?v=m6asOJmfGpY

Title of the video should be
James Powell - More About Generators | PyData London 2018

**Comment by logankilpatrick** [comment]
Great, thank you!
