### ISSUE TITLE
Sebastian Ramirez - Serving ML Easily With FastAPI | PyData Fest Amsterdam 2020

### ISSUE THREAD

**Issue by mycaule** [numfocus/YouTubeVideoTimestamps#49]
Contents
0:00 Introduction
1:45 About FastAPI
2:24 FastAPI Basics
3:22 Support for type annotations
4:17 Concise backend code
6:00 Challenge: serving a machine learning model
7:33 How API routes and documentation work
11:30 Parsing HTTP body and query
18:05 Making ML calls from the API app
23:20 Data validation of the HTTP body
28:52 IDE auto-completion and type checks
30:49 Documenting fields with metadata
32:57 Declaring mandatory fields and validating requests
36:56 Performance
38:27 Additional features
39:50 About typer and thing libraries
41:30 Q&A

Original video at https://www.youtube.com/watch?v=IdlT8l7kHT8

**Comment by logankilpatrick** [comment]
Thanks!
