### ISSUE TITLE
Vincent Warmerdam: The profession of solving (the wrong problem) | PyData Amsterdam 2019

### ISSUE THREAD

**Issue by avvorstenbosch** [numfocus/YouTubeVideoTimestamps#5]
0:00 - Welcome
0:10 - The Profession of Solving (the Wrong Problem)
0:40 - Let's start with a true story
1:00 - Introduction - Assigment for a first year course in statistics 
1:25 - Data from a gig at a local theatre
2:23 - Statistically significant result
3:04 - Realizing what went wrong
5:00 - First story - Designing a recommender system for the NPO
7:00 - Step 1: DrawPictures not DeepLearning
9:00 - Step 2: A/A test this setup!
9:51 - Step 3: alg(B) = entropy
10:41 - Step 4: More Measuring: the order!
11:37 - Step 5: Is it time for DeepLearning?
11:55 - Step 5: not DeepLearning, but DumbThinking
13:13 - Vincent's Lemma: Serendipity (The solution)
16:14 - Gotta Love Heuristics: Lessons
17:45 - Second story - 261 days: a billboard lottery
18:59 - Mathematical formulation of the billboard problem
20:21 - Rephrasing the billboard prolblem
21:21 - Applying rephrasing to a WHO food problem
25:08 - Third story - Kaggle's Santa Problem
26:52 - Mathematical formulation of the problem
27:56 - Everyone was solving the wrong problem
29:42 - Lessons learnt
30:55 - Last story: the condom factory
32:26 - Solution to the condom factory problem
33:30 - Parting words
34:40 - Advice

**Comment by logankilpatrick** [comment]
Really well done! Thank you : )
