### ISSUE TITLE
Ryan Zotti: How to Build Your Own Self Driving Toy Car | PyData DC 2016

### ISSUE THREAD

**Issue by BofeiCHEN** [numfocus/YouTubeVideoTimestamps#50]
Ryan Zotti: How to Build Your Own Self Driving Toy Car | PyData DC 2016
https://www.youtube.com/watch?v=QbbOxrR0zdA&t=1500s

0:00 How to build your own Self-Driving Car
0:51 About Me
3:16 Why I did this project
6:24 Materials
10:26 Internals
13:49 Training Track
19:26 What I’ll demo today
20:19 Car camera demo
21:46 Tech Stack
22:44 Raspberry Pi
24:09 Raspberry Pi vs Arduino
28:58 Hello World for the Pi: LED light
29:41 Gradually added more complexity
30:16 Pro Tip: Don’t inhale lead
31:16 OpenCV
32:32 Haar Cascades
37:50 Stop sign detector
42:35 TensorFlow
44:43 Machine Learning 101
46:49 How a Neural Network “Sees”
50:39 Convoluted Neural Networks
52:06 Deep Learning
52:53 Standard Neural Network
56:20 Tips for tuning Neural Networks
59:11 Tensor Board
1:00:44 GPU Machine Learning
1:02:50 GPUs now commonplace
1:04:28 NVIDIA stock price
1:05:23 Machine Learning takeaways
1:09:01 Car and hardware tips
1:10:58 To Do
1:12:18 That’s it!
1:13:00 Question & Answer

**Comment by BofeiCHEN** [comment]
Ryan Zotti: How to Build Your Own Self Driving Toy Car | PyData DC 2016
https://www.youtube.com/watch?v=QbbOxrR0zdA&t=1500s

0:00 How to build your own Self-Driving Car
0:51 About Me
3:16 Why I did this project
6:24 Materials
10:26 Internals
13:49 Training Track
19:26 What I’ll demo today
20:19 Car camera demo
21:46 Tech Stack
22:44 Raspberry Pi
24:09 Raspberry Pi vs Arduino
28:58 Hello World for the Pi: LED light 
29:41 Gradually added more complexity
30:16 Pro Tip: Don’t inhale lead
31:16 OpenCV
32:32 Haar Cascades
37:50 Stop sign detector
42:35 TensorFlow
44:43 Machine Learning 101
46:49 How a Neural Network “Sees”
50:39 Convoluted Neural Networks
52:06 Deep Learning
52:53 Standard Neural Network
56:20 Tips for tuning Neural Networks
59:11 Tensor Board
1:00:44 GPU Machine Learning
1:02:50 GPUs now commonplace
1:04:28 NVIDIA stock price
1:05:23 Machine Learning takeaways
1:09:01 Car and hardware tips
1:10:58 To Do
1:12:18 That’s it!
1:13:00 Question & Answer

**Comment by logankilpatrick** [comment]
Thanks! This is great.
