### ISSUE TITLE
High Performance Python - Gus Cavanaugh | PyData Global 2021

### ISSUE THREAD

**Issue by Retinpkumar** [numfocus/YouTubeVideoTimestamps#52]
### High-Performance Python - Gus Cavanaugh | PyData Global 2021
[https://www.youtube.com/watch?v=ewaY9CcjLt0](https://www.youtube.com/watch?v=ewaY9CcjLt0)

00:00 Welcome
01:15 Faking a Scientific Workload
02:35 Working with Numba
05:19 About Gus Cavanaugh
07:19 About Rapids. Why do we need it?
12:27 What is Dask?
15:35 Using Dask
20:00 Summarizing everything up to now
23:07 Setting up Rapids
26:00 Running Numba in Dask
28:50 Ways to deploy Dask cluster
29:55 Cost of setting up a Rapids client and Dask cluster
31:05 Running everything in the local machine: The Afar package

**Comment by logankilpatrick** [comment]
Thank you!!
