### ISSUE TITLE
Daniel Kirsch - Functional Programming in Python

### ISSUE THREAD

**Issue by hfzvc** [numfocus/YouTubeVideoTimestamps#53]
[Daniel Kirsch - Functional Programming in Python](https://www.youtube.com/watch?v=r2eZ7lhqzNE)

00:00 Welcome Remarks
00:19 About Me (Daniel Kirsch)
01:06 About This Talk
01:20 Disclaimer - PEP 20
03:19 Vocabulary of Concepts
03:47 Purity (Functions Without Side-Effects)
04:23 First Class Functions
04:54 Higher Order Functions
05:32 Decorators as Higher Order Functions
05:49 Partial Function Application
07:15 Currying
09:05 Interlude: Closures
09:55 Currying Example from the Standard Library
10:53 Functional Collection Transformations (Map, Filter, & Reduce)
11:04 Map
11:39 Filter
12:12 Reduce
14:01 Function Composition
15:16 Example: A Bad CSV Parser (1/3)
15:38 Example: Imperative Python (2/3)
16:18 Example: Functional Python (3/3)
20:35 Example: PySpark
21:26 Example: K-Means
23:15 Main Takeaways
23:53 What is Missing in Python
25:00 Functional Libraries
25:38 Nicer Lambda Syntax
26:05 Other Interesting Stuff
26:16 Other Talks (Where I Have Stolen Material)
27:13 More FP?
27:38 Thank You
28:10 Audience Questions: Do you have a workaround for Immutability?
29:58 Audience Questions: Composition in Python is ugly, any workaround?
31:43 Audience Comment: Cannot assume Pure Function example won't have side-effect.
32:43 Audience Question: Underscore construct in PySpark
34:39 Audience Question: Any Python packages that try to mimic Scala like functional programming?
35:34 Audience Question: List Comprehensions are faster than map(), what is your take?
38:17 Last Question: Have you looked at Hy dialect?

**Comment by logankilpatrick** [comment]
Added, thank you!
