### ISSUE TITLE
Temiloluwa Adeniyi: So Much Data, Such Poor Quality - Temiloluwa Adeniyi | PyData Global 2021

### ISSUE THREAD

**Issue by christianbitter** [numfocus/YouTubeVideoTimestamps#55]
00:35 - Presentation Introduction
01:20 - Overview
01:40 - About Presenter
02:30 - Motivation
05:15 - Covid and Logistics Challenges
09:05 - Finance and Data Quality
11:40 - Health Care and Data Quality
15:05 - Core Elements of Data Quality
17:30 - Data Quality Tools
20:34 - Apache Griffin Demo
21:20 - Apache Atlas Demo
21:50 - Collibra Demo
24:00 - End
24:30 - Q & A

**Comment by logankilpatrick** [comment]
Added, thank you!
