### ISSUE TITLE
Joel Grus: Learning Data Science Using Functional Python | PyData Seattle 2015

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#7]
https://www.youtube.com/watch?v=ThS4juptJjQ&list=WL&index=50

Contents
0:00  -  Introduction
0:45  -  What is functional programming?
2:57  -  Iterators
3:55  -  Generators/Generator comprehensions
6:10  -  itertools
12:30 -  Fibonacci numbers example
15:56 -  Prime numbers example
16:57 -  K-means clustering
26:10 -  Aside: Matplotlib animation for K-means
27:40 -  Gradient Descent
35:17 -  Linear Regression for Stochastic Gradient Descent
37:30 -  End of lecture and Questions

let me know if i can improve something.

**Comment by logankilpatrick** [comment]
Great, thank you!
