### ISSUE TITLE
Julie Hollek: Data Science How do you Even? | PyData Austin 2019

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#8]
https://youtu.be/v6HbJN5R1BM?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ
    
Contents
0:00  - Introduction
1:15  - Speaker's background
6:00  - What is Data Science?
8:35  - Data Science @ Twitter
11:02 - Health Data Science
15:43 - Potentially abusive content and User Controls
22:48 - Suspension evasion
26:15 - Metric Development and Productionization
32:22 - End of lecture 

I saw that here name is written as Julia, ending with an 'a', but it ends with an 'e'. Check the slide at the beginning of the video.

**Comment by logankilpatrick** [comment]
Great, thank you on both fronts!
