### ISSUE TITLE
Felix Wyss: Jupyter Notebooks in Visual Studio Code | PyData Indy 2019

### ISSUE THREAD

**Issue by stobinaator** [numfocus/YouTubeVideoTimestamps#9]
https://youtu.be/9ibDpXRg1ac?list=PLrreiQzMtASRWlvA20GiuN4qukHrjWhAZ

Contents
0:00 - Introduction
2:10 - Hands-on
4:25 - Data Viewer for Pandas or NumPy
5:00 - Questions

**Comment by logankilpatrick** [comment]
Can we add some more detail here?

**Comment by stobinaator** [comment]
Contents
0:00 - Introduction
2:10 - Demo in VSC
3:12 - Faster and easier check of local variables
4:09 - Look graph directly in VSC in a new window
4:35 - Dynamic Data Viewer for Pandas or NumPy
5:00 - Questions

is this better?

**Comment by logankilpatrick** [comment]
Yes, thank you!
